from passlib.hash import phpass

hash = '$P$BpZ5/N6Fw.G4HP8ppj1HFmk8CfP.kD0'
passwords = [
    '111', '123', '123123', '123321', '1234', '12345', '123456', '1234567',
    '12345678', '123456789', '1234567890', '123abc', '666', '999', '000',
    'aaaaaa', 'abc123', 'alberto', 'alexandra', 'alexandro', 'amanda',
    'andrea', 'angel', 'angels', 'anthony', 'asdf', 'asdfasdf', 'ashley',
    'babygirl', 'baseball', 'basket', 'basketball', 'blahblah', 'bubbles',
    'buster', 'butterfly', 'carlos', 'charlie', 'cheese', 'chocolate',
    'computer', '#1dad', 'diablo', 'dragon', 'elite', 'estrella',
    'flower', 'football', 'forum', 'freedom', 'friends', 'hi',
    'hello', 'hunter', 'iloveu', 'iloveyou', 'internet', 'jennifer', 'jessica', 'jesus',
'jordan',
'joshua',
'justin',
'killo',
'letmein',
'liverpool',
'lovely',
'loveme',
'loveyou',
'lovemama',
'#1mama',
'merlin',
'monkey',
'mustang',
'nicole',
'nothing',
'number1',
'pass',
'passport',
'password',
'password1',
'playboy',
'pokemon',
'pretty',
'princess',
'purple',
'pussy',
'qazwsx',
'qwerty',
'roberto',
'sebastian',
'secret',
'shadow',
'shit',
'soccer',
'starwars',
'sunshine',
'superman',
'tequiero',
'test',
'testing',
'trustno1',
'tweety',
'welcome',
'westside',
'whatever',
'windows',
'writer',
'zxcvbnm',
'zxczxc'
    # Add the rest of your passwords here
]

for password in passwords:
    if phpass.verify(password, hash):
        print(f"The password is: {password}")
        break